name: PHA_Guardian
version: "0.0.10"
slug: "pha_guardian"
description: "this is a very serious application :) "
 
arch:
  - aarch64
startup: services
boot: auto
host_network: true 

build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19


